### ISSUE TITLE
Feature Request: Display "pinned issues"

### ISSUE THREAD

**Issue by christf** [penguineer/ActionablesWeb#4]
Append redmine with a field for pinning issues and then additionally display those issues on the overview page

**Comment by penguineer** [comment]
How does the pinning in Redmine work?
Issues for extending Redmine would be better placed in the Redmine upstream development.

**Comment by christf** [comment]
redmine allows to add additional fields to issues that are b eyond the default data model of redmine.

**Comment by penguineer** [comment]
Wouldn't this rather be something for an extra service that delivers "pinned" issues and then maybe this can be incorporated here?

For this tool I'm thinking more along the line of changing it so that it can be embedded in other pages, so that building a dashboard becomes easier.

**Comment by penguineer** [comment]
Have a look at https://github.com/penguineer/RedmineActionablesCollector for the service that collects data for this one. A similar service should be setup for the "pinned" issues.
(I am pro having this service, at I could use it in various scenarios!)

**Comment by penguineer** [comment]
> redmine allows to add additional fields to issues that are b eyond the default data model of redmine: https://www.redmine.org/projects/redmine/wiki/RedmineCustomFields

I don't see a way to set a custom field that is specific to a user. If I put a "pinned" boolean, all users would see the same set of pinned issues.

**Comment by penguineer** [comment]
I do not see a solution to this Request without breaking independence from Redmine or a specific Redmine installation.
